name = "LiquidElectrolytes"
uuid = "5a7dfd8c-b3af-4c8d-a082-d3a774d75e72"
version = "2.2.0"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de>", "Steffen Maaß", "Rene Kehl", "Hong Zhao"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LessUnitful = "f29f6376-6e90-4d80-80c9-fb8ec61203d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
VoronoiFVM = "82b139dc-5afc-11e9-35da-9b9bdfd336f3"

[weakdeps]
ExtendableFEM = "a722555e-65e0-4074-a036-ca7ce79a4aed"

[extensions]
LiquidElectrolytesExtendableFEMExt = "ExtendableFEM"

[compat]
Aqua = "0.8.11"
Colors = "0.12, 0.13.0"
DataFrames = "1.7.0"
DelimitedFiles = "1.9.1"
DocStringExtensions = "0.9.3"
DoubleFloats = "1.4.3"
ExampleJuggler = "2.2.1"
ExplicitImports = "1.11.1"
ExtendableFEM = "0.9.0, 1"
ExtendableGrids = "1.12.0"
ForwardDiff = "0.10.35,0.11, 1"
GridVisualize = "1.12.0"
HypertextLiteral = "0.9.5"
InteractiveUtils = "1"
Interpolations = "0.15.1"
LessUnitful = "1.1"
LinearAlgebra = "1"
Markdown = "1"
NLsolve = "4"
PhysicalConstants = "0.2.3"
Pkg = "1"
Pluto = "0.20.5"
PlutoUI = "0.7.62"
PreallocationTools = "0.4.27, 1"
Printf = "1"
ProgressLogging = "0.1.4"
ProgressMeter = "1.7"
SciMLBase = "2"
StaticArrays = "1.6.0"
Test = "1"
UUIDs = "1"
Unitful = "1.22.0"
VoronoiFVM = "2.8.0,3"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
ExampleJuggler = "3bbe58f8-ed81-4c4e-a134-03e85fcf4a1a"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
ExtendableFEM = "a722555e-65e0-4074-a036-ca7ce79a4aed"
ExtendableGrids = "cfc395e8-590f-11e8-1f13-43a2532b2fa8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GridVisualize = "5eed8a63-0fb0-45eb-886d-8d5a387d12b8"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Aqua", "Colors", "DataFrames", "DelimitedFiles", "DoubleFloats", "ExampleJuggler", "ExplicitImports", "ExtendableFEM", "ExtendableGrids", "ForwardDiff", "GridVisualize", "HypertextLiteral", "InteractiveUtils", "Interpolations", "LinearAlgebra", "Markdown", "NLsolve", "Pkg", "Pluto", "PlutoUI", "Printf", "StaticArrays", "Test", "UUIDs", "Unitful"]
